{{- if .Values.gateway.enabled }}
{{- $listenerPort := ternary (default 443 .Values.gateway.tls.listenerPort) .Values.gateway.listenerPort .Values.gateway.tls.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    {{- include "navigator.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className | quote }}
  listeners:
    - name: grpc
      protocol: {{ if .Values.gateway.tls.enabled }}HTTPS{{ else }}HTTP{{ end }}
      port: {{ $listenerPort }}
      {{- if .Values.gateway.tls.enabled }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ .Values.gateway.tls.secretName }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
