{{- if and .Values.gateway.enabled .Values.gateway.tls.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "navigator.fullname" . }}-gateway-pki
  labels:
    {{- include "navigator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "navigator.fullname" . }}-gateway-pki
subjects:
  - kind: ServiceAccount
    name: {{ include "navigator.fullname" . }}-gateway-pki
    namespace: {{ .Release.Namespace }}
{{- end }}
